"""refactor tables

Revision ID: 2f9d23e492d0
Revises: ba96781ca047
Create Date: 2024-09-01 19:46:43.054219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f9d23e492d0'
down_revision: Union[str, None] = 'ba96781ca047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_browsings_id', table_name='user_browsings')
    op.drop_table('user_browsings')
    op.drop_index('ix_user_purchases_id', table_name='user_purchases')
    op.drop_table('user_purchases')
    op.drop_table('user_histories')
    op.add_column('reviews', sa.Column('helpful', sa.String(), nullable=True))
    op.drop_column('reviews', 'sentiment')
    op.add_column('reviews', sa.Column('sentiment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'sentiment',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('reviews', 'helpful')
    op.create_table('user_histories',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_histories_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_histories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_purchases',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purchase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='user_purchases_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user_histories.user_id'], name='user_purchases_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_purchases_pkey')
    )
    op.create_index('ix_user_purchases_id', 'user_purchases', ['id'], unique=False)
    op.create_table('user_browsings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('browse_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='user_browsings_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user_histories.user_id'], name='user_browsings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_browsings_pkey')
    )
    op.create_index('ix_user_browsings_id', 'user_browsings', ['id'], unique=False)
    # ### end Alembic commands ###
